services:
  express:
    build: ./express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - N8N_URL=http://n8n:5678
    restart: unless-stopped
    depends_on:
      - flask
      - n8n

  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: